### ISSUE TITLE
README updates

### ISSUE THREAD

**Issue by cjbj** [PhilCorcoran/oracle-json#21]
A few small corrections for the README I noted when I skimmed through it:

> Requires the node oracle driver module.

This should be 'oracledb'.  The 'oracle' module is/was different.

> Due to underlying dependency on oracledb modele nodejs compatibility is >= 6

Now you've updated to node-oracledb 4, the dependency is Node.js 8.16+, 10.16+ or 12.

**Comment by PhilCorcoran** [comment]
Thanks for the corrections
